### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by S-TE11A** [MrXiaoM/qsign#11]
```log
2023-09-08 07:20:43 I/QSignService: register 365xxxx049
2023-09-08 07:21:37 W/stderr: Sep 08, 2023 7:21:37 AM moe.fuqiuluo.unidbg.env.FileResolver resolve
2023-09-08 07:21:37 W/stderr: WARNING: Couldn't find file: /mnt/sdcard/jly1/
2023-09-08 07:21:37 W/stderr: Sep 08, 2023 7:21:37 AM moe.fuqiuluo.unidbg.env.FileResolver resolve
2023-09-08 07:21:37 W/stderr: WARNING: Couldn't find file: /mnt/sdcard/jly1/a
2023-09-08 07:21:51 I/QSignService: energy 810_9
2023-09-08 07:22:24 I/Bot.365xxxx049: Calculating type 2 PoW, it can take some time....
2023-09-08 07:22:26 I/Bot.365xxxx049: Got PoW result, cost: 1509 ms
请使用 SakuraLoginSolver 打开 http://<ip>:22333/request/request/37414212 来完成验证
2023-09-08 07:22:42 I/QSignService: energy 810_2
2023-09-08 07:22:47 W/QSignService: with CoroutineName(SendMessage)
java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.base/java.util.ArrayList$Itr.remove(Unknown Source)
        at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:182)
        at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
        at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
        at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:262)
        at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.Module.emulateFunction(Module.java:163)
        at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
        at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:52)
        at qsign-1.1.0-beta.mirai2.jar//com.tencent.mobileqq.channel.ChannelManager.onNativeReceive(ChannelManager.kt:29)
        at qsign-1.1.0-beta.mirai2.jar//moe.fuqiuluo.api.UnidbgFetchQSign.submit(UnidbgFetchQSign.kt:258)
        at qsign-1.1.0-beta.mirai2.jar//top.mrxiaom.qsign.QSignService$callback$1.invokeSuspend(QSignService.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-09-08 07:22:47 I/Bot.365xxxx049: Bot cancelled: Bot closed
2023-09-08 07:22:47 E/main: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: java.lang.IllegalStateException: running
                at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:352)
                at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.thread.Function64.run(Function64.java:39)
                at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
                at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
                at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
                at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
                at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:262)
                at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.Module.emulateFunction(Module.java:163)
                at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
                at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.linux.android.dvm.DvmObject.callJniMethodObject(DvmObject.java:93)
                at qsign-1.1.0-beta.mirai2.jar//com.tencent.mobileqq.qsec.qsecdandelionsdk.Dandelion.energy(Dandelion.kt:11)
                at qsign-1.1.0-beta.mirai2.jar//moe.fuqiuluo.api.UnidbgFetchQSign.customEnergy(UnidbgFetchQSign.kt:38)
                at qsign-1.1.0-beta.mirai2.jar//moe.fuqiuluo.api.UnidbgFetchQSign$customEnergy$1.invokeSuspend(UnidbgFetchQSign.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
                at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
                at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
                at qsign-1.1.0-beta.mirai2.jar//top.mrxiaom.qsign.QSignService.encryptTlv(QSignService.kt:64)
                at net.mamoe.mirai.internal.network.protocol.packet.TlvKt.t544ForVerify(Tlv.kt:1013)
                at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin2$SubmitSliderCaptcha$1$1$1$1.invoke(WtLogin2.kt:35)
                at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin2$SubmitSliderCaptcha$1$1$1$1.invoke(WtLogin2.kt:28)
                at net.mamoe.mirai.utils.TlvMapKt._writeTlvMap(TlvMap.kt:130)
                at net.mamoe.mirai.utils.TlvMapKt._writeTlvMap$default(TlvMap.kt:123)
                at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin2$SubmitSliderCaptcha$1$1$1.invoke(WtLogin2.kt:28)
                at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin2$SubmitSliderCaptcha$1$1$1.invoke(WtLogin2.kt:25)
                at net.mamoe.mirai.internal.network.protocol.packet.EncryptMethodEcdh.makeBody(EncryptMethod.kt:121)
                at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.writeOicqRequestPacket(OutgoingPacket.kt:455)
                at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.writeOicqRequestPacket$default(OutgoingPacket.kt:448)
                at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin2$SubmitSliderCaptcha$1$1.invoke(WtLogin2.kt:25)
                at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin2$SubmitSliderCaptcha$1$1.invoke(WtLogin2.kt:24)
                at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.writeSsoPacket(OutgoingPacket.kt:985)
                at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.writeSsoPacket$default(OutgoingPacket.kt:352)
                at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin2$SubmitSliderCaptcha$1.invoke(WtLogin2.kt:24)
                at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin2$SubmitSliderCaptcha$1.invoke(WtLogin2.kt:23)
                at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.buildLoginOutgoingPacket(OutgoingPacket.kt:310)
                at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.buildLoginOutgoingPacket$default(OutgoingPacket.kt:278)
                at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin2.SubmitSliderCaptcha(WtLogin2.kt:23)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:472)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                ... 6 more
Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: running]

2023-09-08 07:22:47 V/Bot.365xxxx049: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Failure@fbbd90c
2023-09-08 07:22:47 I/main: mirai-console started successfully.
```

**Comment by S-TE11A** [comment]
自动登录后报错导致，应该是登录失败了，请问如何解决？

**Comment by S-TE11A** [comment]
可能是性能不足的关系，增加到8C4G之后 现在不会报上述错误了，但是在energy阶段100%会崩溃
![image](https://github.com/MrXiaoM/qsign/assets/20638533/fb333ece-a566-44bb-b638-9a4bd0c3061e)

**Comment by S-TE11A** [comment]
会出现各种各样的崩溃错误
![image](https://github.com/MrXiaoM/qsign/assets/20638533/b5aad7b7-d3d9-49ee-857c-7b67bcd83f6d)

**Comment by S-TE11A** [comment]
还是会触发一楼的报错，已经把配置加到8C8G了，应该和配置没关系了，想请问下可能是什么原因导致的，感谢！

**Comment by MrXiaoM** [comment]
unidbg 问题，无源码，无力处理
