### ISSUE TITLE
1.0.8 启动失败

### ISSUE THREAD

**Issue by Andy-Chuck** [MrXiaoM/qsign#6]
使用 1.0.8 之后 MCL 启动失败，日志在下方文件中。
[log.log](https://github.com/MrXiaoM/qsign/files/12380060/log.log)

排查问题时删除了 Qsign 以外的所有插件，也无法启动。操作系统是 Windows 2012，JDK 17. 
1.0.7 使用正常。
![1](https://github.com/MrXiaoM/qsign/assets/54295429/78616d5d-d25c-425b-896b-598b6323e4be)

**Comment by Redlnn** [comment]
貌似读配置文件时炸了

```log
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property basePath has not been initialized
        at qsign-1.0.8.mirai2.jar//top.mrxiaom.qsign.QSignService$Factory$Companion.getBasePath(QSignService.kt:139)
        at qsign-1.0.8.mirai2.jar//top.mrxiaom.qsign.PluginMain.onLoad(PluginMain.kt:42)
```
