### ISSUE TITLE
使用新版登陆成功后闪退

### ISSUE THREAD

**Issue by Tamamoimoto** [MrXiaoM/qsign#7]
2023-08-28 19:14:25 I/org.quartz.impl.StdSchedulerFactory: Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2023-08-28 19:14:25 I/org.quartz.impl.StdSchedulerFactory: Quartz scheduler version: 2.3.2
2023-08-28 19:14:25 I/org.quartz.core.QuartzScheduler: Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2023-08-28 19:14:25 I/yPlug: 启动时间 ： Mon Aug 28 19:14:25 CST 2023
2023-08-28 19:14:25 I/MiraiNative: Mirai Native 正启用所有插件。
2023-08-28 19:14:25 I/MiraiNative: /mnt/disk01/bot/data/org.itxtech.mirainative/plugins/linux/aarch64/Dice.Driver.CQ.dll
>  terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast
./mcl: line 3:  3650 Aborted                 $ JAVA_BINARY -Dmirai.resource.creation.stack.enabled=true -Dmirai.BotConfiguration.autoReconnectOnForceOffline=false -Dmirai.slider.captcha.supported -jar mcl-2.1.2-all.jar $*

系统：Linux armbian 5.15.58-flippy-75+o # 148 SMP PREEMPT Sat Jul 30 11:32:27 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

是内存不足吗，大概空闲1G的内存启动的。

**Comment by Tamamoimoto** [comment]
旧版1.0.4能使用，但是过段时间签名就会炸掉。
[92m2023-08-28 02:15:32 I/Bot.208388298: Reconnected successfully in 58.287s.[0m[m
[93m2023-08-28 02:15:32 W/QSignService: with CoroutineName(SendMessage)[m
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.[m
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:249)[m
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)[m
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)[m
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)[m
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)[m
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)[m
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)[m
	Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException[m
Caused by: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.[m
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)[m
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)[m
	... 6 more[m
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(208388298), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)[m
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)[m
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)[m
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)[m
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)[m
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)[m
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)[m
		... 5 more[m
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(208388298), code=40, title=安全提醒, message=请确认你输入了正确的账号。该账号存在被盗风险，已进入保护模式，请前往安全中心恢复。, errorInfo=
